# Generated by Django 4.1.2 on 2024-03-08 09:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=1000)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 794146, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 794456, tzinfo=datetime.timezone.utc))),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField()),
                ('cite_comment', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('media', models.IntegerField()),
                ('tag_ids', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 795821, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 795837, tzinfo=datetime.timezone.utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=1000)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 801795, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 801812, tzinfo=datetime.timezone.utc))),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airp.author')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 798629, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 798652, tzinfo=datetime.timezone.utc))),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airp.author')),
                ('citation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airp.citation')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airp.source')),
            ],
        ),
        migrations.CreateModel(
            name='CiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 796926, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateField(default=datetime.datetime(2024, 3, 8, 9, 18, 1, 796953, tzinfo=datetime.timezone.utc))),
                ('citation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airp.citation')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
