# Generated by Django 4.1.2 on 2024-03-09 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 410531, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 410834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='citation',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 412156, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='citation',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 412177, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='citereview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 413456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='citereview',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 413482, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 414958, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 414982, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 419676, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='source',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 10, 7, 49, 419722, tzinfo=datetime.timezone.utc)),
        ),
    ]
