# Generated by Django 3.2.4 on 2022-11-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='communication_style',
            field=models.JSONField(null=True),
        ),
    ]
